### ISSUE TITLE
Fails to install from github on macos

### ISSUE THREAD

**Issue by tommedema** [breuerfelix/chromedriver-py#24]
```
pip install git+https://github.com/breuerfelix/chromedriver-py.git
Collecting git+https://github.com/breuerfelix/chromedriver-py.git
  Cloning https://github.com/breuerfelix/chromedriver-py.git to /private/var/folders/11/829w0h653zn4z81jgf0mv48r0000gp/T/pip-req-build-ulsmukns
  Running command git clone --filter=blob:none --quiet https://github.com/breuerfelix/chromedriver-py.git /private/var/folders/11/829w0h653zn4z81jgf0mv48r0000gp/T/pip-req-build-ulsmukns
  Resolved https://github.com/breuerfelix/chromedriver-py.git to commit 72d3ad828f6f60da93421e5a52b932dc700d2008
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/11/829w0h653zn4z81jgf0mv48r0000gp/T/pip-req-build-ulsmukns/setup.py", line 9, in <module>
          with open(CURRENT_VERSION_FILE) as f:
      FileNotFoundError: [Errno 2] No such file or directory: './CURRENT_VERSION.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by breuerfelix** [comment]
the install from github doesn't work, due to the fact how the pipeline runs. the bundled binaries are only included in the pypi repos. i will note that in the readme today when fixing the latest version :)
