### ISSUE TITLE
Open chrome failed with error message "selenium.common.exceptions.WebDriverException: Message: Service /binbin/pymilvus-test/lib/python3.8/site-packages/chromedriver_py/chromedriver_linux64 unexpectedly exited"

### ISSUE THREAD

**Issue by binbinlv** [breuerfelix/chromedriver-py#25]
chromedriver-py Version: 109.0.5414.25
machine version:
Linux version 4.18.0-372.16.1.el8_6.x86_64 (mockbuild@dal1-prod-builder001.bld.equ.rockylinux.org) (gcc version 8.5.0 20210514 (Red Hat 8.5.0-4) (GCC)) #1 SMP Wed Jul 13 15:36:40 UTC 2022

Reproduced script:
```
>>> from selenium import webdriver
>>> from selenium.webdriver.chrome.service import Service
>>> from chromedriver_py import binary_path
>>> service_object = Service(binary_path)
>>> driver = webdriver.Chrome(service=service_object)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/binbin/pymilvus-test/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/binbin/pymilvus-test/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 103, in __init__
    self.service.start()
  File "/binbin/pymilvus-test/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 106, in start
    self.assert_process_still_running()
  File "/binbin/pymilvus-test/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 119, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /binbin/pymilvus-test/lib/python3.8/site-packages/chromedriver_py/chromedriver_linux64 unexpectedly exited. Status code was: 12
```

**Comment by breuerfelix** [comment]
Thats more related to chromedriver itself. Maybe you should open an Issue there, and explain your setup. The package works as expeceted but chromedriver quits somehow. Maybe try a different version? A different System?

Or maybe try to search what the exit code 12 means.
