### ISSUE TITLE
Unable to run find binary after built to .exe

### ISSUE THREAD

**Issue by tommytang213** [breuerfelix/chromedriver-py#29]
The python script to call the chrome browser can be run in .py format. However, it fails to run after built to .exe file. The error is as below: (I ran the script on window 10)

Traceback (most recent call last):
  File "Assign_Pollvote.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "chromedriver_py\__init__.py", line 38, in <module>
  File "chromedriver_py\__init__.py", line 33, in _get_filename
Exception: Couldn't find a binary for your system: windows / amd64. Please create an Issue on github.com/breuerfelix/chromedriver-py and include this Message.

![image](https://github.com/breuerfelix/chromedriver-py/assets/61879201/c50d733f-7d41-4d86-be67-a2898855bb48)

**Comment by breuerfelix** [comment]
could you have a look at #26 ? he had the same problem as you :)

**Comment by breuerfelix** [comment]
awesome, thanks for the feedback!
